### PR TITLE
Runtime overhaul, part 1

### PR DESCRIPTION
**Pull request by cher-nov**

### CODE REVIEW

**Review by notviri — APPROVED** [review]

**Review by skyfloogle — CHANGES_REQUESTED** [review]
You marked the following functions as not needing context, but they actually do:
- draw_sprite_pos
- action_linear_step
- action_potential step
- action_create_object_random
- action_kill_position
- action_draw_background (it needs relative, that's an error on our part)
- action_draw_*
- move_random
- place_snapped
- mp_linear_step(_object)
- mp_linear_path(_object)
- mp_potential_path(_object)
- mp_grid_add_instances (self/other detection)
- instance_exists (self/other detection, oops)
- instance_number (self/other detection, oops)
- instance_copy
- instance_sprite

These functions you aliased have some differences between them:
- action_message takes a string, show_message takes anything and converts accordingly
- Likewise action_if_question and show_question
- action_splash_web has an execute_shell call in it that splash_show_web doesn't? Not sure what that one's about
- action_replace_background seems to function a little differently from background_replace, among other things by supporting more formats
- min3 and max3 have argcounts listed in the function table (unlike min and max which take any number), and I think those get checked sometimes?

variable\_\*\_exists and variable\_\*\_get consumed a variable slot if available in GM8 too, but that only really matters for savestates (which already aren't a compatible format atm), so as long as we write that down somewhere it's probably fine.

Good work otherwise, pure functions especially could potentially allow for some compile-time evaluation.

**Comment by cher-nov** [comment]
> * action_replace_background seems to function a little differently from background_replace, among other things by supporting more formats

How? And support for more formats doesn't seem like something that could introduce incompatibility, does it?

> * min3 and max3 have argcounts listed in the function table (unlike min and max which take any number), and I think those get checked sometimes?

They actually don't, but I just replaced the direct calls which didn't have these checks before as well.
I wonder if it would better to implement them as simplier (hence faster) versions of `min` / `max`, just with two consecutive comparisons instead of iterating the whole argument list.

> variable_*_exists and variable_*_get consumed a variable slot if available in GM8 too, but that only really matters for savestates (which already aren't a compatible format atm), so as long as we write that down somewhere it's probably fine.

It should be compatible anyway, just like if `variable_*_exists()` and `variable_*_get()` weren't called at all, shouldn't it?

> Good work otherwise, pure functions especially could potentially allow for some compile-time evaluation.

Thank you. This is literally what I ~~plan~~ hope to implement just a bit later, maybe also with replacing sequential calls of constant functions with a single one. This is a common anti-pattern, for example:

```gml
for ({var i; i=0}; i < string_length(s); i += 1) {
  // some code that doesn't change the value of 's'
}
```
***
Other remarks are entirely true, I will correct them ASAP.

**Comment by skyfloogle** [comment]
> How? And support for more formats doesn't seem like something that could introduce incompatibility, does it?
True. I didn't look all that closely, they just looked a bit different so I noted it down.
Having looked a bit closer, `action_background_replace` actually takes less arguments (and handles file-not-found errors differently), so they really are just different.

> It should be compatible anyway, just like if `variable_*_exists()` and `variable_*_get()` weren't called at all, shouldn't it?
If `variable_*_exists` allocates a slot in the variable name table in GM8 and not in the emulator, you could craft an edge case that checks whether some variables exist, then sets them in a different order, which would map the variable names to different IDs and break savestate compatibility. As I said, though, I don't even know if we evaluate variable names in the same order for them to be compatible in the first place.

**Comment by cher-nov** [comment]
> If `variable_*_exists` allocates a slot in the variable name table in GM8 and not in the emulator, you could craft an edge case that checks whether some variables exist, then sets them in a different order, which would map the variable names to different IDs and break savestate compatibility.

To be honest, I would just suggest to provide backward compatibility with savestates (that is, loading GM saves in gm8emu), but not forward (which is the vice-versa), because this can limit us to the framework of GM behaviour.

**Review by Adamcake — APPROVED** [review]

**Review by skyfloogle — APPROVED** [review]

**Review by notviri — APPROVED** [review]

**Pull request merged**
